title: Welcome to my Blog!
description: My Personal Blog
author: yzg
logo: /myblog/static/img/avatar.png
github: https://github.com/Youzhigang
about: 一个会python的页面仔

baseurl: /


# share:
#   twitter_username: \#
#   fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
